### ISSUE TITLE
K8s manual deployment files cause validation errors w/ "_NOTE0", "_NOTE1", "_NOTE2"

### ISSUE THREAD

**Issue by michael-read** [lagom/activator-lagom-java-chirper#103]
Deployment files such as  lagom-java-chirper-example/deploy/kubernetes/resources/chirper/activity-stream-impl-statefulset.json that contain the following cause validation errors w/ "_NOTE0", "_NOTE1", "_NOTE2":

              {
                "_NOTE0": "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
                "_NOTE1": "!!! Be sure to change APPLICATION_SECRET's value (below) before deploying !!!",

                "name": "APPLICATION_SECRET",
                "value": "changeme!",

                "_NOTE2": "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
},

Maybe page @ https://developer.lightbend.com/guides/lagom-kubernetes-k8s-deploy-microservices/ should make a note of the fact that these need to be removed before deploy to k8s. Maybe I'm picking nits but I would think we should avoid errors that need to be tracked down by someone trying to play with this.

**Comment by longshorej** [comment]
Thanks for the report. I'll look into this.
