### ISSUE TITLE
Websockets close after 85seconds or so.

### ISSUE THREAD

**Issue by BarDweller** [lagom/activator-lagom-java-chirper#108]
Hi.. I was trying to learn about how all this stuff worked, so I signed into Chirper, added an account, then added a few chirps.. I noticed if I left the browser alone for more than a couple of minutes, any new chirps posted would not appear in the chirp feed.. 

Then I connected a websocket client to ws://localhost:9000/api/activity/chirper  and saw that when I published a chirp, it would appear in this feed.. and after about 85seconds of no new chirps, the socket would be closed by the server. 

Thinking maybe I needed to do websocket PING/PONG handling to hold the connection open, I build a client to connect to the websocket and send PING messages, the server dutifully replied with PONG messages, but at 85 seconds or so, I'd notice I was still disconnected, even if I'd sent a PING message literally seconds before.

So I went hunting, and found I could increase the idle-timeout, and the linger-timeout for the akka http layer, that the websockets were running over.. I increased both to 1hour, for all 3 chirper services, (by adding the properties as system properties to the build.sbt in the same manner as http.port etc are per impl image.. then rebuilt, and redeployed.. 

Now, when I connect to ws://localhost:9000/api/activity/chirper, I stay connected for 85seconds or so, and then I get a stack trace output by activityservice and my socket closes.

```
activityservice    | [application-akka.actor.default-dispatcher-3] ERROR activityservice - Exception in PathCallId{pathPattern='/api/activity/:userId/live'}
activityservice    | java.io.IOException: Connection reset by peer
activityservice    |    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
activityservice    |    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
activityservice    |    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
activityservice    |    at sun.nio.ch.IOUtil.read(IOUtil.java:192)
activityservice    |    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
activityservice    |    at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
activityservice    |    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
activityservice    |    at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
activityservice    |    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
activityservice    |    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
activityservice    |    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
activityservice    |    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
activityservice    |    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
activityservice    |    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
activityservice    |    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
activityservice    |    at java.lang.Thread.run(Thread.java:748)
```

My client reports the following close information for the socket.. 
Connection closed.
Close status: 1011 (Internal Server Error)
Close reason: {"name":"Exception","detail":""}

Thinking that maybe this stack trace was from activityservice discovering it's connection to another service had broken (the impl for getLiveActivityStream seems to invoke chirpservice at least).. I wondered if this meant Lagom was not sending ping/pong frames between services.. 

I tested, by adding a new service to activity that ticked every 5 minutes.. this service with no other dependencies behaves interestingly... 

- When connected to with a client with no ping/pong handling, the connection is closed by the server after ~85 seconds. (Fwiw, I'm using 'dark websocket terminal' a chrome browser app).
- When connected to with a client that DOES have ping/pong handling, the connection remains open (at least past 10minutes+ .. I'll admit to not waiting the full hour before typing all this up)

My conclusion is somewhere, there's a timeout at 85seconds that I haven't been able to alter. And that this 85 second timeout is breaking chirper when I raise the idle-timeout and linger-timeout to 1hour, because when there are no new chirps, there's no app traffic on the socket between chirp and activity service, leading to a stack trace which I think is indicating the connection is busted. 

I guess either I need a way to raise that 85second threshold to the same 1h I have set for the others, or I need a way to have Lagom enable ping/pong frame handling for it's service to service calls over websockets.. 

Either would be useful!

**Comment by BarDweller** [comment]
If you'd like to try the version I'm running .. my fork is over at https://github.com/BarDweller/lagom-java-chirper-example 

It's using docker compose as it's runtime, but I do not believe that compose is the issue here. 

If you want to test with it (the timeouts are still set at 1h, (see changes to build.sbt) .. you can .. 
```
sbt -DbuildTarget=compose clean docker:publishLocal
cd deploy/compose
docker-compose up -d cassandra web locator proxy
#wait 15 seconds or so..
docker-compose up -d chirpservice friendservice activityservice
#wait 15 seconds or so..
#visit http://localhost:9000/ in a browser (if you get a 503, then you need to wait longer for the services to come up)
#Create a user, and post a chirp
#Use a websocket client to open the socket ws://localhost:9090/api/activity/USERNAME/live
#see the chirp you chirped.. 
#wait about 2 minutes.. 
#Boom.
#docker-compose logs activityservice will show the stacktrace
#http://localhost:8500 shows the service status in consul
```
If you don't have nodejs, you'll need it to be able to build the sbt stuff.. 
```
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
nvm install --lts
```

**Comment by BarDweller** [comment]
2 Solutions.. 

a) swap ` -Dakka.http.server.idle-timeout=1h -Dakka.http.server.linger-timeout=1h` for each service to `-Dplay.server.http.idleTimeout=1h`. The latter property seems to have something extra that setting the akka timeouts doesn't affect.

b) swap back to the netty http server, connections seem to behave as expected with that impl.

Leaving this open in case it's worth investigating further, or updating docs with info.. 

Things that still don't seem right.. 
- when using the akka http server, lagom doesn't seem to count websocket ping/pong messages as traffic sufficient to hold open a websocket. 
- akka configuration DOES affect the websocket timeout, but not totally, with chirper, raising the akka timeout allows the initial connection to the activity stream to continue past 85seconds (when using ping/pong frames from client).. but you get the stack trace above when backend service to service calls discover _their_ socket connection went away (because they don't use ping/pong frames). This is rather odd, as it means sockets using ping/pong to hold them open now stay open till the akka configured limit, but sockets without ping/pong are being killed by some other process at the 85second idle mark. I suspect that other process is configured via the `play.server.http.idleTimeout` property. This feels inconsistent at best.
- https://www.playframework.com/documentation/2.6.x/SettingsAkkaHttp doesn't mention the odd interactions of the akka/play http properties.
- Chirper on the new akka http server is kind of broken, especially the front end, that has no idea that it's activity feed has terminated. 85 Seconds is too short for an app like Chirper. Imagine if your Twitter feed page stopped updating any tweets you sent after 85 seconds of idle.. Chirper likely exists this way because it was created on the netty server that had longer timeouts, and it's not been re-evaluated since the move to the new one. The quick fix is to increase the timeout to something more friendly to Chirper (15minutes? 1hour?) .. The better fix is to have the UI detect when the websocket is closed, and decide if it should reconnect based on if the browser tab is still active (at the very least it should reconnect if disconnected, and a user begins interacting with the page, eg, typing a new chirp)

**Comment by ignasi35** [comment]
Hi @BarDweller I finally managed to reproduced the error and captured this output on the `sbt runAll` logs:

```
2018-02-21T23:16:48.243Z [warn] akka.actor.ActorSystemImpl [sourceThread=application-akka.actor.default-dispatcher-25, akkaSource=akka.actor.ActorSystemImpl(application), sourceActorSystem=application, akkaTimestamp=23:16:48.242UTC] - HTTP header 'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits' is not allowed in requests
2018-02-21T23:18:12.650Z [error] akka.actor.ActorSystemImpl [sourceThread=application-akka.actor.default-dispatcher-28, akkaSource=akka.actor.ActorSystemImpl(application), sourceActorSystem=application, akkaTimestamp=23:18:12.650UTC] - Websocket handler failed with The connection closed with error: Connection reset by peer
akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
```

The timestamps between the traces demonstrate the 85s you referred to originally. I think I'm observing 85s of inactivity on the websocket though: if I keep sending chirps on the UI every 10 seconds the websocket will never close.

**Comment by BarDweller** [comment]
Note that the github repo I linked above now has the `play.server.http.idleTimeout` set to 2 hours via the sbt build file. To recreate behavior described in this issue using that repo, you'll have to tweak the build file to remove that and use the `akka.http.server` configuration properties instead.

The behavior you experienced would be consistent with what I saw, that regardless of what setting you configure for `akka.http.server.idle-timeout` and `akka.http.server.linger-timeout`, that sockets with no traffic will close after 85 seconds. Sockets with real application traffic (chirps in this case) will remain open indefinitely.

You'll have to experiment with a client that tries holding open the connection using websocket ping frames to see more of what happens if you hold open a connection to say, the activity feed endpoint, while lagom won't use ping frames to hold open the connection between activity and chirper, leading to interesting collapse when the activity chirper link shuts down after ~85secs, (with a stack trace in the activity service console), leading to subsequent close of the client socket.

**Comment by ignasi35** [comment]
@BarDweller this margin of error between the configured [`75s`](https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/resources/reference.conf#L25) and the actual `~85s` you observed is caused by [a bug in Akka's handling of timeouts](https://github.com/akka/akka/issues/24616). Good catch! Would have gone undetected without your accurate description.

There's few more details to discuss in your comments above. Will keep this issue open.

**Comment by TimMoore** [comment]
Note there is a pull request to fix the Akka issue at https://github.com/akka/akka/pull/24618. Thanks @ignasi35!

What other changes should we make to Lagom, Play or this example?

Also related to #11.

**Comment by ignasi35** [comment]
> What other changes should we make to Lagom, Play or this example?

1. As suggested by @BarDweller the service-to-service communication via websockets could be reviewed to ensure the websockets remain open. ATM, I haven't tested the various combinations of client-to-server combinations to see what's the current behavior.

2. Also, I could reproduce the difference in behavior wrt Play's `idleTimeout` setting. Play should setup both the Netty backend and the AkkaHTTP backend so that behavior is consistent but I'm not sure Netty closes the connection (as discovered by @BarDweller).

3. The Chirper application could demo re-connection as mentioned in #11 or, alternatively, use a different UI closer to twitter where an alert showing there's new tweets are available. That alert could be a long poll and only when clicked a new websocket would be opened.

**Comment by ignasi35** [comment]
This repository has been archived in favour of the specialised:

 - [lagom-java-sbt-chirper-example](https://github.com/lagom/lagom-java-sbt-chirper-example/) which is a fork of this but only uses `sbt`.
 - [lagom-java-maven-chirper-example](https://github.com/lagom/lagom-java-maven-chirper-example/) which is a fork of this but only uses `Maven`.
