### ISSUE TITLE
Websocket connection management

### ISSUE THREAD

**Issue by huntc** [lagom/activator-lagom-java-chirper#11]
There is no websocket connection management code presently. This creates a problem if the front end is opened by a browser but the other services are not yet available. In addition, those other services (chirp, activities etc) can come and go, and this would cause the browser resident front end code to fail.

Note also that, particularly where bi-directional functionality isn't required, SSE may be a better way to go. Browsers manage SSE connections.

**Comment by ignasi35** [comment]
Related https://github.com/lagom/lagom/issues/269

**Comment by ignasi35** [comment]
This repository has been archived in favour of the specialised:

 - [lagom-java-sbt-chirper-example](https://github.com/lagom/lagom-java-sbt-chirper-example/) which is a fork of this but only uses `sbt`.
 - [lagom-java-maven-chirper-example](https://github.com/lagom/lagom-java-maven-chirper-example/) which is a fork of this but only uses `Maven`.
