### ISSUE TITLE
invalid HTTP port , when running after sbt docker:publishLocal

### ISSUE THREAD

**Issue by psriramula** [lagom/activator-lagom-java-chirper#114]
When generated docker images using sbt docker:publishLocal unable to start the docker container using docker run -p 9000:9000 <generated docker image>

**Comment by TimMoore** [comment]
Are you passing in all of the required environment variables when running?

The Docker configuration in this project is really intended to be used along with Kubernetes, not by running each container manually. Have a look at the Kubernetes configuration files in https://github.com/lagom/lagom-java-chirper-example/tree/master/deploy/kubernetes/resources/chirper to see the environment variables that are being passed through to each service (including the HTTP port).

You might also be interested in this fork by a community member who has converted the project to work with Docker Compose: https://github.com/BarDweller/lagom-java-chirper-example.

**Comment by psriramula** [comment]
thanks @TimMoore , I shall have a look
