### ISSUE TITLE
unable to build docker images with sbt docker:stage

### ISSUE THREAD

**Issue by psriramula** [lagom/activator-lagom-java-chirper#115]
Given the current sbt/docker config 
when generated docker staging using : sbt docker:stage
Then I am unable to build a Docker image 

See the log below 

docker build -t prasadchirper:wip .
Sending build context to Docker daemon   57.6MB
Step 1/7 : FROM openjdk:8-jre-alpine
8-jre-alpine: Pulling from library/openjdk
ff3a5c916c92: Pull complete 
5de5f69f42d7: Pull complete 
fa7536dd895a: Pull complete 
Digest: sha256:154ecdda6eaada1929b4b8ea94cce9f1fef7cf62b6779d686fd1aa0d30248f2d
Status: Downloaded newer image for openjdk:8-jre-alpine
 ---> b1bd879ca9b3
Step 2/7 : RUN ["/bin/sh", "-c", "apk add --no-cache bash && ln -sf /bin/bash /bin/sh"]
 ---> Running in cdbc39e8a3a7
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/6) Installing pkgconf (1.3.10-r0)
(2/6) Installing ncurses-terminfo-base (6.0_p20171125-r0)
(3/6) Installing ncurses-terminfo (6.0_p20171125-r0)
(4/6) Installing ncurses-libs (6.0_p20171125-r0)
(5/6) Installing readline (7.0.003-r0)
(6/6) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
Executing busybox-1.27.2-r7.trigger
OK: 90 MiB in 56 packages
Removing intermediate container cdbc39e8a3a7
 ---> ec388fcbb26d
Step 3/7 : WORKDIR /opt/docker
Removing intermediate container 05f10d7ed6e5
 ---> 53a3336a87b3
Step 4/7 : ADD --chown=daemon:daemon opt /opt
ADD failed: stat /var/lib/docker/tmp/docker-builder616975422/opt: no such file or directory

**Comment by TimMoore** [comment]
Which directory are you running `docker build` in?

I was able to build an image with this sequence of commands:

```bash
sbt clean docker:stage
cd chirp-impl/target/docker/stage/
docker build .
```

**Comment by psriramula** [comment]
Thanks @TimMoore , I managed to get my head around the sbt-native packager , It did worked for me just last night.
