### ISSUE TITLE
duplicate entry: public/main.css

### ISSUE THREAD

**Issue by thinkmorestupidless** [lagom/activator-lagom-java-chirper#117]
I see this message from the `front-end` module when doing `docker:publishLocal` on `master`

**Comment by octonato** [comment]
Do you have any indication of which entry is duplicated? That will help fix it. That's probably something on this file: https://github.com/lagom/lagom-java-chirper-example/blob/master/front-end/src/main/resources/public/main.css

**Comment by thinkmorestupidless** [comment]
hmmm, no indication of anything within the file - it just tells me it's `public/main.css` and i can't find another file with that name so assumed it was that one.

**Comment by longshorej** [comment]
Can you try running `sbt clean` and then `sbt docker:publishLocal`?

**Comment by thinkmorestupidless** [comment]
Interesting, `clean` didn't help but manually deleting the `/target` directories and rebuilding DID fix it - thanks for the suggestion
