### ISSUE TITLE
failed to start because akka-dns not in maven central

### ISSUE THREAD

**Issue by jorgheymans** [lagom/activator-lagom-java-chirper#121]
This project references akka-dns which hasn't made it to maven central yet, hence 
```
mvn lagom:runAll
...
[ERROR] Failed to execute goal com.lightbend.lagom:lagom-maven-plugin:1.4.2:runAll (default-cli) on project lagom-java-chirper: Execution lagom-internal-request of goal com.lightbend.lagom:lagom-maven-plugin:1.4.2:start failed: Failed to start service friend-impl: Could not find artifact ru.smslv.akka:akka-dns_2.12:jar:2.4.2                              
```

See https://github.com/ilya-epifanov/akka-dns/issues/10

**Comment by ignasi35** [comment]
@jorgheymans I think the issue is that today bintray is having [intermitent outages](https://bintray.statuspage.io/):

https://github.com/lagom/lagom-java-chirper-example/blob/ca8528235728ab50b4fa0ab76eb5ae5024df3969/pom.xml#L168-L175

**Comment by jorgheymans** [comment]
Oh I see, thanks!

We're behind a corporate proxy and Nexus mirror, pom specified repositories
are always problematic. Hopefully it gets published to maven central soon.

**Comment by TimMoore** [comment]
@jorgheymans: try using https://github.com/lagom/lagom-java-sbt-chirper-example or https://github.com/lagom/lagom-java-maven-chirper-example as these no longer require this dependency.
