### ISSUE TITLE
Add a disclaimer and remove this repo

### ISSUE THREAD

**Issue by ignasi35** [lagom/activator-lagom-java-chirper#124]
Since the creation of https://github.com/lagom/lagom-java-sbt-chirper-example and https://github.com/lagom/lagom-java-maven-chirper-example this repo is no longer relevant. 

We should either removed it, or add a clear disclaimer on `README` informing users of the new location of the repos and motivation for the migration.

**Comment by ignasi35** [comment]
Bonus points: update links on https://www.lagomframework.com/documentation/1.4.x/java/LagomExamples.html#Learning-more-from-Lagom-examples and https://www.lagomframework.com/documentation/1.4.x/scala/LagomExamples.html#Learning-more-from-Lagom-examples

**Comment by benmccann** [comment]
This seems like it'll make the example harder to maintain because every change (besides those to the build system) will now have to be made in two places

**Comment by TimMoore** [comment]
Yes, it could, but we decided to make the tradeoff of harder maintenance in favor of making it easier for users to understand the contents of the repositories and instructions. This repo is mixing too many different ideas, and has become very difficult to use as an example of what to do in your own projects.

At this point, the application itself has been very stable, and most of the changes _are_ to the build.

For changes that don't touch the build, you can add both of the split GitHub repos as remotes to the same local git repo, and then cherry-pick changes between different branches based on each remote.

Changes that touch both the build and something else will be a little more effort, but it's still manageable (e.g., by splitting the commits).

**Comment by TimMoore** [comment]
Also updated the description of the repository in GitHub to point to the new ones
