### ISSUE TITLE
No check on operations ?

### ISSUE THREAD

**Issue by thibaultmeyer** [lagom/activator-lagom-java-chirper#21]
Actually it was possible to request "chirps" of users not flag as "friends" and API il requestable without authentication / token.

Maybe it would be nice to add auth mecanism / security check to this example.

Thanks

**Comment by jroper** [comment]
Hi @0xbaadf00d, I know this is an old issue, but we're not likely to add this to chirper because https://github.com/lagom/online-auction-java is our "canonical" sample app, and we're going ot demonstrate authorization in that.
