### ISSUE TITLE
Chirp tables may fail to be created if cassandra is not up

### ISSUE THREAD

**Issue by dotta** [lagom/activator-lagom-java-chirper#24]
The chirp table are created as part of the chirp service initialization https://github.com/lagom/activator-lagom-java-chirper/blob/master/chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java#L52-L64. If Cassandra is not up (e.g., it's in the process of being started), then the chirp tables won't be created. To avoid the issue, the table should be created only when a connection with the Cassandra server can be established.

**Comment by huntc** [comment]
Nice work!
