### ISSUE TITLE
Bintray credentials are required to run the app

### ISSUE THREAD

**Issue by JustinPihony** [lagom/activator-lagom-java-chirper#26]
After [the pull request that added bintray publishing](https://github.com/lagom/activator-lagom-java-chirper/pull/14) simply using the `runAll` command will fail if you do not have a bintray credentials file set up. This is an issue at root with sbt-bintray. However, this should be removed from here until it is resolved at the root.

The current workaround is to create the credentials file, or remove the lines added in the referenced PR.

**Comment by JustinPihony** [comment]
Root issue is found at https://github.com/softprops/bintray-sbt/issues/88

**Comment by dotta** [comment]
I can't reproduce the issue (I've removed my local `~/.bintray` folder, and run `runAll` on this' repo master branch, but it works fine for me).

**Comment by huntc** [comment]
Could it be in some other ~/.sbt folder that you have your credentials?

**Comment by dotta** [comment]
I guess I might, but I couldn't find it. I'm not sure I understand how credentials are being resolved then, as I was under the impression that sbt-bintray would always use   `~/.bintray/.credentials`.

I guess I'll have to start with a clean machine to reproduce this.

**Comment by dotta** [comment]
Alright, I can see the warnings now when executing `runAll`

```
[warn] Credentials file /Users/mirco/.bintray/.credentials does not exist
```

Though, services are started and chirper is running despite the warnings. My understanding is that @huntc [has recommended](https://github.com/lagom/activator-lagom-java-chirper/pull/14#issuecomment-233529697) removing sbt-bintray-bundle, so I'll create a PR to revert the changes in https://github.com/lagom/activator-lagom-java-chirper/pull/14
