### ISSUE TITLE
Add ConductR video + shell script documentation

### ISSUE THREAD

**Issue by markusjura** [lagom/activator-lagom-java-chirper#4]
Once the ConductR video is hosted on http://www.lightbend.com/lagom we need add this link to tutorial: https://github.com/lagom/activator-lagom-java-chirper/blob/master/tutorial/index.html

Also we should provide documentation for the bundle configuration of the `fron-end` project: https://github.com/lagom/activator-lagom-java-chirper/blob/master/front-end/bundle-configuration/default/runtime-config.sh

**Comment by markusjura** [comment]
https://github.com/lagom/activator-lagom-java-chirper/pull/12 addresses the latter point with the bundle configuration.

**Comment by dotta** [comment]
@markusjura I guess this issue can be closed.
