### ISSUE TITLE
circuitbreaker page broken

### ISSUE THREAD

**Issue by benmccann** [lagom/activator-lagom-java-chirper#65]
I get the following error in the Chrome debugger:

circuitbreaker.js:8 WebSocket connection to 'ws://localhost:27462/_status/circuit-breaker/stream' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by TimMoore** [comment]
@benmccann do you still see this? It is working for me with the latest `master`.

If you're still seeing an error, the next thing I would ask is to check the port number against the ones printed on the console when you `runAll`.

**Comment by benmccann** [comment]
I'm out of town right now, so don't have my computer to be able to check. I'll try again in a couple weeks when I return

**Comment by TimMoore** [comment]
Sure no problem. Sorry it took this long to review this.

**Comment by TimMoore** [comment]
@benmccann just checking in on this again. Please let us know if you're still seeing problems with this page.

**Comment by benmccann** [comment]
Looks like it's fixed now
