### ISSUE TITLE
Getting 404 while trying to interact with chirper-front-end miroservice

### ISSUE THREAD

**Issue by andrei-l** [lagom/activator-lagom-java-chirper#74]
I've setup chirper app via `sbt runAll`, logs stated everything is fine:
```
[info] Cassandra server running at 127.0.0.1:4000
[info] Service locator is running at http://localhost:8000
[info] Service gateway is running at http://localhost:9000
[info] Service load-test-impl listening for HTTP on 0:0:0:0:0:0:0:0:51796
[info] Service activity-stream-impl listening for HTTP on 0:0:0:0:0:0:0:0:51855
[info] Service front-end listening for HTTP on 0:0:0:0:0:0:0:0:57143
[info] Service friend-impl listening for HTTP on 0:0:0:0:0:0:0:0:60399
[info] Service chirp-impl listening for HTTP on 0:0:0:0:0:0:0:0:54485
```

So I opened front-end (http://localhost:57143/) and tried to register\login. Unfortunately I didn't succeed in it. What I noticed from browser logs is that the POST request was sent to http://localhost:57143/api/users and failed with 404:

```
        <h1>Action Not Found</h1>

        <p id="detail">
            For request 'POST /api/users'
        </p>
```

As I understand this request should have been either sent to friend-impl microsrvice directly or forwarded somehow by front-end microservice. And from what I see, front-end microservice doesn't have any expected POST routes:

```
        return new RoutingDsl()
                // Index
                .GET("/").routeTo(application::index)
                .GET("/signup").routeTo(application::index)
                .GET("/addFriend").routeTo(application::index)
                .GET("/users/:id").routeTo(application::userStream)
                .GET("/cb").routeTo(application::circuitBreaker)

                // Assets
                .GET("/assets/*file").routeAsync((String file) ->
                        assets.at("/public", file, false).asJava()
                                .apply(requestHeader()).run(materializer))
                .GET("/webjars/*file").routeAsync((String file) ->
                        webJars.at(file).asJava()
                                .apply(requestHeader()).run(materializer))

                .build().asScala();
```

When I made a POST request to friend-impl microservice manually, I managed to create a user. Tried later on to login with it to front-end microservice but got similar 404 error.

**Comment by guizmaii** [comment]
Have you tried to pass via the `http://localhost:9000` url ? Normally you should not talk directly to the microservices. You should talk to the proxy (`9000`) which will redirect your requests to the concerned services.

**Comment by andrei-l** [comment]
@guizmaii right... I somehow missed the idea about service gateway microservice, didn't realize that it is aggregates all public API and is an entry point basically.  I thought that I should use every single microservice separately. 

Thanks for pointing me to that. 

I'm closing the ticket as it is not a valid issue.
