### ISSUE TITLE
All Services running but Lagom failed to load front end api-- it shows Action not found on browser

### ISSUE THREAD

**Issue by ejiro-precious** [lagom/activator-lagom-java-chirper#85]
Action Not Found
For request 'GET /'
These routes have been tried, in this order:
1GET\Q/api/users/\E([^/]+)Service: friendservice (http://0.0.0.0:56866)
2POST\Q/api/users\EService: friendservice (http://0.0.0.0:56866)
3POST\Q/api/users/\E([^/]+)\Q/friends\EService: friendservice (http://0.0.0.0:56866)
4GET\Q/api/users/\E([^/]+)\Q/followers\EService: friendservice (http://0.0.0.0:56866)
5POST\Q/api/chirps/live/\E([^/]+)Service: chirpservice (http://0.0.0.0:52002)
6GET\Q/api/chirps/live\EService: chirpservice (http://0.0.0.0:52002)
7GET\Q/api/chirps/history\EService: chirpservice (http://0.0.0.0:52002)
8GET\Q/api/activity/\E([^/]+)\Q/live\EService: activityservice (http://0.0.0.0:53713)
9GET\Q/api/activity/\E([^/]+)\Q/history\EService: activityservice (http://0.0.0.0:53713)

All services are running but it refuse to load front end on a browser

**Comment by TimMoore** [comment]
@ejiro4precious are you still having this problem with the latest version of `master`?

If so, please provide output from when you run Chirper.

**Comment by ejiro-precious** [comment]
Noo it has been resolved. Thanks

**Comment by octonato** [comment]
Ok, in that case I'm closing this one.
