### ISSUE TITLE
instructions for using an external cassandra server ?

### ISSUE THREAD

**Issue by paulczar** [lagom/activator-lagom-java-chirper#86]
It would be great to show how to modify the kubernetes manifests to show using an external cassandra database, as many folks would be not be comfortable running cassandra in kubernetes (or in a container in general) and may be existing an cassandra db or a cloud provided managed cassandra.

**Comment by TimMoore** [comment]
For demonstration purposes, I think it's best to keep things simple and straightforward. Nobody will be running Chirper in production, and they probably wouldn't want it using their production Cassandra cluster.

The Lagom documentation covers configuring Cassandra contact points directly: https://www.lagomframework.com/documentation/1.4.x/java/ProductionOverview.html#Using-static-Cassandra-contact-points

The new Lightbend Orchestration for Kubernetes documentation also covers configuration of external services: https://developer.lightbend.com/docs/lightbend-orchestration-kubernetes/latest/features.html#external-services
