### ISSUE TITLE
JVM options for Docker (Java 8)

### ISSUE THREAD

**Issue by guizmaii** [lagom/activator-lagom-java-chirper#95]
Shouldn't we use the JVM options `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` in order to tell to the JVM to use the `cgroup` resources into account instead of the host resources ?

More informations on these options: https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

**Comment by longshorej** [comment]
Thanks @guizmaii - good idea. We've got some DC/OS & Marathon examples in-flight so once they're completed we'll look into this, unless you get to it first of course :wink:

**Comment by guizmaii** [comment]
I made a PR: https://github.com/lagom/lagom-java-chirper-example/pull/96

Do you want to add the resources limits/requests in the Kubernetes pods description ?

**Comment by guizmaii** [comment]
In you opinion, should we use this flag: `-XX:MaxRAMFraction=1` ??

Based on this discussion on Twitter (https://twitter.com/codepitbull/status/934384652806221825), some people consider it unsafe because of offheap allocations but the default value `4` seems not good enougth.

I'm not an expert on this subject, maybe you are ? :)

**Comment by guizmaii** [comment]
Maybe this tweet give also some more info: https://twitter.com/bosyr/status/934421885517025281

And more info here too: https://www.slideshare.net/ErnstR001/java-and-cgroups-eng

**Comment by TimMoore** [comment]
Resolved in #96
