### ISSUE TITLE
Profile / Reduce Memory Limits

### ISSUE THREAD

**Issue by longshorej** [lagom/activator-lagom-java-chirper#99]
For Kubernetes & Marathon, we could measure how much memory the services use and update the k8s/marathon metadata accordingly.

Per @huntc in #97:

> Tip: Use pmap to profile - you may get away with considerably less than that.

**Comment by TimMoore** [comment]
@longshorej is this still an ongoing concern? (I'm trying to figure out which issues need to be migrated to the new repos.)

**Comment by ignasi35** [comment]
This repository has been archived in favour of the specialised:

 - [lagom-java-sbt-chirper-example](https://github.com/lagom/lagom-java-sbt-chirper-example/) which is a fork of this but only uses `sbt`.
 - [lagom-java-maven-chirper-example](https://github.com/lagom/lagom-java-maven-chirper-example/) which is a fork of this but only uses `Maven`.
